import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Style from '@/styles/Home.module.css'
import Heart from '../public/svg/heart.svg'
import Heart2 from '../public/svg/heart2.svg'
import Chat from '../public/svg/chat.svg'
import Dot from '../public/svg/dots.svg'
import Send from '../public/svg/send.svg'
import Comment from '../public/svg/comment.svg'
import Homes from '../public/svg/home.svg'
import Search from '../public/svg/search.svg'
import Add from '../public/svg/add.svg'
import Reel from '../public/svg/reel.svg'
import Profile from '../public/svg/profile.svg'
import Save from '../public/svg/save.svg'
import Link from 'next/link'
import ReactPlayer from 'react-player'
import { useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isStoryActive, setIsStoryActive] = useState(false);
  const [heartColor, setHeartColor] = useState(false)
  const toggleStoryActive = () => {
    setIsStoryActive(!isStoryActive);
  };
  const toggleHeart = () => {
    setHeartColor(!heartColor);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* navbar */}
      <div className={Style.container}>
        <nav className={Style.navbar}>
          <div className={Style.flex_nav}>
            <div className={Style.logo}>
              <img src="https://www.pngmart.com/files/21/Instagram-PNG-Transparent.png" alt="" />
            </div>
            <div className={Style.flex_icon}>
              <Image className={Style.icon} src={Heart} />
              <Image className={Style.icon} src={Chat} />
            </div>
          </div>
        </nav>
        <div className={Style.content} >
          <div className={Style.story_section}>
            {/* <div className={Style.story_sec_flex}> */}
            <div className={Style.story_images}>
              <div className={`${Style.story_section_img_name} ${isStoryActive ? Style.active_story : ''
                }`}
                onClick={toggleStoryActive}
              >
                <img className={Style.story_img} src="https://images.unsplash.com/photo-1535615615570-3b839f4359be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8bGlnaHQlMjBoZWFydHxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80" alt="" />
                <p>Your Story</p>
              </div>
              <div className={Style.story_section_img_name}>
                <img className={Style.story_img} src="https://pbs.twimg.com/media/FwgI8wuaEAIGL1L?format=jpg&name=small" alt="" />
                <p>RM</p>
              </div>
              <div className={Style.story_section_img_name}>
                <img className={Style.story_img} style={{ background: '#ffffff61', color: '#ffffffa3' }} src="https://lh3.googleusercontent.com/47bi6kNTTwsc21QgIW8YL92OVdjvl3CLyhLcfPTR9L290dLFRAgINDVe17LFKwc2RbOKUOA-D_9GMQ_v2MrM_EL-TFgo5_A9bqR0MuxwcfL9VQ=w960-rj-nu-e365" alt="" />
                <p style={{ color: '#ffffffa3' }}>j.m</p>
              </div>
              <div className={Style.story_section_img_name}>
                <img className={Style.story_img} src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0UG0VraXJOI61sEgnf09yH_uIUTr5lCCIINzMIBpbFaOHOWWnegZzeScEad5OkRv1h_M&usqp=CAU" alt="" />
                <p >thv</p>
              </div>
              <div className={Style.story_section_img_name}>
                <img className={Style.story_img} style={{ background: '#ffffff61', color: '#ffffffa3' }} src="https://lh3.googleusercontent.com/47bi6kNTTwsc21QgIW8YL92OVdjvl3CLyhLcfPTR9L290dLFRAgINDVe17LFKwc2RbOKUOA-D_9GMQ_v2MrM_EL-TFgo5_A9bqR0MuxwcfL9VQ=w960-rj-nu-e365" alt="" />
                <p style={{ color: '#ffffffa3' }}>j.m</p>
              </div>
              <div className={Style.story_section_img_name}>
                <img className={Style.story_img} src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0UG0VraXJOI61sEgnf09yH_uIUTr5lCCIINzMIBpbFaOHOWWnegZzeScEad5OkRv1h_M&usqp=CAU" alt="" />
                <p >thv</p>
              </div>
            </div>
          </div>
          <main className={Style.main}>
            <section>
              <div className={Style.header}>
                <div className={Style.left_nav}>
                  <img className={Style.left_nav_img} src='https://images.freeimages.com/images/large-previews/34e/williamstown-1057646.jpg' alt="" />
                  <h3>John_doe</h3>
                </div>
                <Image src={Dot} className={Style.icon} />
              </div>
              <div className={Style.post}>
                <img src="https://moon.nasa.gov/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaUlEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7ea93725388fa8cabc5e8cee2d45580b630b245f/wrinkle-ridge-mare-crisium-thumb.jpg?disposition=inline" alt="" srcset="" />
              </div>
              <div className={Style.post_footer}>
                <span className={Style.left_icon}>
                  {/* <Image onClick={toggleHeart} className={`${Style.icon} ${heartColor ? Style.red_heart : ''}`} src={Heart} /> */}
                  {heartColor ? (
                    <Image
                      className={Style.icon}
                      src={Heart2}
                      onClick={toggleHeart}
                    />
                  ) : (
                    <Image
                      className={Style.icon}
                      src={Heart}
                      onClick={toggleHeart}
                    />
                  )
                  }
                  <Image className={Style.icon} src={Comment} />
                  <Image className={Style.icon} src={Send} />
                </span>
                <Image src={Save} className={Style.icon} />
              </div>
              <div className="liked_section">
                {/* <Image className={Style.icon} src={Like} onClick={() => { }} /> */}
              </div>
            </section>
            <section>
              <div className={Style.header}>
                <div className={Style.left_nav}>
                  <img className={Style.left_nav_img} src="https://images.freeimages.com/images/large-previews/a6f/williamstown-1057657.jpg" alt="" />
                  <h3>unicorn_girl</h3>
                </div>
                <Image src={Dot} className={Style.icon} />
              </div>
              <div className={Style.post}>
                <img src="https://media.cntraveler.com/photos/5ea9df878abbf81d02aeae0b/1:1/w_4016,h_4016,c_limit/Kawachi-Fuji-Garden-wisteria-GettyImages-684691336.jpg" alt="" srcset="" />
              </div>
              <div className={Style.post_footer}>
                <span className={Style.left_icon}>
                  <Image className={Style.icon} src={Heart} />
                  <Image className={Style.icon} src={Comment} />
                  <Image className={Style.icon} src={Send} />
                </span>
                <Image src={Save} className={Style.icon} />
              </div>
            </section>
            <section>
              <div className={Style.header}>
                <div className={Style.left_nav}>
                  <img className={Style.left_nav_img} src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0UG0VraXJOI61sEgnf09yH_uIUTr5lCCIINzMIBpbFaOHOWWnegZzeScEad5OkRv1h_M&usqp=CAU" alt="" />
                  <h3>thv</h3>
                </div>
                <Image src={Dot} className={Style.icon} />
              </div>
              <div className={Style.post}>
                <img src="https://readdork.com/wp-content/uploads/2023/08/V-album.jpg" alt="" srcset="" />
              </div>
              <div className={Style.post_footer}>
                <span className={Style.left_icon}>
                  <Image className={Style.icon} src={Heart} />
                  <Image className={Style.icon} src={Comment} />
                  <Image className={Style.icon} src={Send} />
                </span>
                <Image src={Save} className={Style.icon} />
              </div>
            </section>
          </main>
        </div>
        <div className={Style.footer}>
          <Image className={Style.icon} src={Homes} />
          <Image className={Style.icon} src={Search} />
          <Image className={Style.icon} src={Add} />
          <Image className={Style.icon} src={Reel} />
          <Image className={Style.icon} src={Profile} />
        </div>
      </div>
      <div>
        <Link href="https://github.com/vensi9/next-insta-clone" className={Style.github_btn}>
          See on GitHub
        </Link>
      </div>

    </>
  )
}
